sudo: false
language: python
addons:
  apt:
    packages:
      - npm
python:
  - "3.7"

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=py37

install:
  - pip install tox-travis
script:
  - tox
